- name: Brew setup
  hosts: all
  gather_facts: true
  vars:
    version: 1.23.4
    brew_bin: "{{ ansible_env.HOME }}/.linuxbrew/bin"

  tasks:
    - name: install list of brew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      environment:
        PATH: "{{ brew_bin }}:{{ ansible_env.PATH }}"
      loop:
        - gh
        - lazygit
        - ripgrep
        - fzf
        - xclip
        - gcc
        - sqlc
        - pgformatter
