# community.general.homebrew:
#     name: foo
#     state: presentq
- name: Brew setup
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if Homebrew is already installed
      command: which brew
      register: brew_check
      ignore_errors: true

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git
      when: brew_check.rc != 0
      become: true

    - name: Clone Homebrew repo (user-local install)
      git:
        repo: https://github.com/Homebrew/brew
        dest: "{{ ansible_env.HOME }}/.linuxbrew/Homebrew"
        version: master
      become: false

    - name: Create Homebrew directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ansible_env.HOME }}/.linuxbrew/bin"
        - "{{ ansible_env.HOME }}/.linuxbrew/etc"
        - "{{ ansible_env.HOME }}/.linuxbrew/sbin"
        - "{{ ansible_env.HOME }}/.linuxbrew/var"
      become: false

    - name: Create symlink to brew
      file:
        src: "{{ ansible_env.HOME }}/.linuxbrew/Homebrew/bin/brew"
        dest: "{{ ansible_env.HOME }}/.linuxbrew/bin/brew"
        state: link
      become: false

    - name: Add Homebrew to PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'eval "$($HOME/.linuxbrew/bin/brew shellenv)"'
        create: yes
      become: false


