- name: docker setup
  hosts: all
  gather_facts: true
  tasks:
    - name: remove existing docker packages
      apt:
        name: "{{ item }}"
        state: absent
        # become: true
      loop:
        - docker.io
        - docker-doc
        - docker-compose
        - docker-compose-v2
        - podman-docker
        - containerd
        - runc

    - name: update
      apt:
        update_cache: yes
      become: true
    - name: ca-certificates, curl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
      become: true
    # sudo install -m 0755 -d /etc/apt/keyrings
    - name: keyring 
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: true 
    # sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - name: download docker gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      become: true
    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker
      become: true

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: install docker packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      become: true
