- name: kubernetes install 
  hosts: all
  gather_facts: true
  become: true
  tasks:
#     # temporarily disable docker service
#     #sudo systemctl stop docker
#     - name: stop docker service
#       ansible.builtin.systemd:
#         name: docker
#         state: stopped
#       when: ansible_distribution == "Ubuntu"
#     # sudo systemctl stop containerd
#     - name: stop containerd service
#       ansible.builtin.systemd:
#         name: containerd
#         state: stopped
#       when: ansible_distribution == "Ubuntu"
# # sudo rm -rf /run/containerd
#       # name: remove containerd run directory
#     - name: remove containerd run directory
#       ansible.builtin.file:
#         path: /run/containerd
#         state: absent
#       become: true
      


    # - name: snap install k8s 
    #   ansible.builtin.command: snap install k8s --classic
    #   when: ansible_distribution == "Ubuntu"
    - name: k8s bootstrap
      ansible.builtin.command: k8s bootstrap
      when: ansible_distribution == "Ubuntu"
      become: true
    - name: k8s status
      ansible.builtin.command: k8s status
      when: ansible_distribution == "Ubuntu"
      register: k8s_status_output
      become: true
    
    - name: Show k8s status
      ansible.builtin.debug:
        var: k8s_status_output.stdout
    
    - name: k8s kubectl get all
      ansible.builtin.command: k8s kubectl get all --all-namespaces
      when: ansible_distribution == "Ubuntu"
      register: k8s_get_all_output
      become: true
    
    - name: Show kubectl output
      ansible.builtin.debug:
        var: k8s_get_all_output.stdout
