- name: nvim
  hosts: all
  gather_facts: true
  tasks:
    - name: install list of apts
      ansible.builtin.apt:
        name:
          - git
          - npm 
          - nodejs
          - python3.12-venv
          - unzip
        state: present
        update_cache: true
      become: true
    - name: snap install neovim
      community.general.snap:
        name: nvim
        state: present
        classic: true
      become: true
    - name: git clone git@github.com:alterejoe/notes.git
      ansible.builtin.git:
        repo: git@github.com:alterejoe/notes.git
        dest: /home/altjoe/notes
    - name: git clone git@github.com:alterejoe/notes.git
      ansible.builtin.git:
        repo: git@github.com:alterejoe/nvim-config.git
        dest: /home/altjoe/.config/nvim
      

      

      


