- name: Ubuntu proxmox vm
  hosts: all
  gather_facts: true
  tasks:
    # - name: install qemu 
    #   ansible.builtin.apt:
    #     name: qemu-guest-agent
    #     state: present
    #     update_cache: true
    #   become: true
    #     ## systemctl enable qemu-guest-agent
    #
    # - name: apt install git
    #   ansible.builtin.apt:
    #     name: git
    #     state: present
    #   become: true
    - name: install list of apts
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
        state: present
        update_cache: true
      become: true
    - name: enable qemu-guest-agent
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started
      become: true
    - name: install cloud-init
      ansible.builtin.apt:
        name: cloud-init
        state: present
      become: true
      

      

      


